language: python
python:
- '3.6'
script: true
deploy:
  provider: pypi
  user: fridex
  password:
    secure: vrrx+XB007AB6qov8NOpe61dJBa8eEvefYLjt+d0RLvFvoFk7wgSgC2MLv4w4d2fsa7SfmriGMnE5ygcAu44uGJd68hU/DtCechp2fpx8xloio9NFcVHQIYkOszXcvwSkPpIrYIkjaEVZfr/wwNSwTYL7+NE28VL1ccaJqR8bzCu8ADtGQzMpOIyBPuJgXvMBF75jxzzu51IU+hb5CpJ8LK++hCt5mlJOuSPWN964dSWQbijQZ9TSudPgJ+YBxJLSAsq2e5g030tv/7Zv5XAdy3bU5cmvpH+yTV+2DLMdLQx2qNDGTqWxfWXbqHS8WA0Kk0rEOKuMwJ/pVrll2POOeHMhLd1J6R6E3+sAGeLL4J2M3JGgAxvZFxRXNPGd0VJ5GI84h0if/zLgSd5L4GU4ujqVV7SDBK7++wls31cmJ8DcOMwd30Xc5SSYGMlJnMm7G0lI39LVUb7BIPHyr8CXo1A+vo+o2N+OOqWkshbP/4KImJB+DY4qR9aDbRYkLyngUDKmAFYCTA+r/B7IurX8S1LjsShm9DwrwKnrtcrNXShellM7ZeYSrPpN9CJyA5mQ4gZylKFxLbL2yBceb1mj2+Zg6Xlk429om1XCE8kvltBPOX/9o6UHnuUUnrZGXrd9jeRoB0hROvXV21eaQLZYny4/tg5KnN/ywgaQevHW/8=
  on:
    tags: true
    branch: master
  distributions: sdist bdist_wheel
