---
apiVersion: v1
kind: Template
metadata:
  annotations:
    description: "This is Nepthys Secret Config"
    openshift.io/display-name: "Nepthys Secret"
    tags: "thoth,ai-stacks,nepthys"
    template.openshift.io/documentation-url: "https://github.com/thoth-station/nepthys/"
    template.openshift.io/long-description: "This is Nepthys used for automatic package releases and updates."
    template.openshift.io/provider-display-name: "Red Hat, Inc."
    version: "1.0.0"
  labels:
    app: thoth
    component: nepthys
    template: nepthys-secret
  name: nepthys-secret

objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: thoth
        component: nepthys
      name: nepthys-secret
    type: kubernetes.io/ssh-auth
    stringData:
      ssh-privatekey: "${NEPTHYS_SSH_PRIVATE_KEY}"
      user-name: "${GITHUB_USER}"
      user-email: "${GITHUB_USER_EMAIL}"
      github-oauth-token: "${GITHUB_TOKEN}"

parameters:
  - description: "Using SSH private key to authenticate the public key set in GitHub."
    displayName: "SSH Private Key"
    name: NEPTHYS_SSH_PRIVATE_KEY
    required: true

  - description: "User account to be used for git commits."
    displayName: "GITHUB USERNAME"
    name: GITHUB_USER
    required: true

  - description: "User email to be used for git commits."
    displayName: "GITHUB USERNAME"
    name: GITHUB_USER_EMAIL
    required: true

  - description: "Github personal oauth token required for merge request."
    displayName: "GITHUB TOKEN"
    name: GITHUB_TOKEN
    required: true
